### ISSUE TITLE
Add debugger compaitibility for supported languages

### ISSUE THREAD

**Issue by proffapt** [proffapt/code-runner#9]
#### Currently debugger support is available for following languages: 
- C
- C++
- Javascript
- Haskell

Adding debugging compatibility will enable the runner to be more versatile.

**Comment by sahil-sagwekar2652** [comment]
Is this issue still open? I would like to work on adding support for python.

**Comment by proffapt** [comment]
> Is this issue still open? I would like to work on adding support for python.

This issue will never be closed, the project will keep on increasing.

**Comment by proffapt** [comment]
This is has met its purpose
